### ISSUE TITLE
Typo in dialog.md documentation

### ISSUE THREAD

**Issue by sleepycharlyy** [poeticAndroid/homegirl_pro#1]
Hey there,
I just wanted to tell you that there's a Typo in the dialog.md documentation (/system_drive/docs/libs/dialog.md)
` 28:  win:attach("prompt", Dia.Promt:new("Hey there!", "What's your name?"))`
you wrote `Dia.Promt:new()` instead of `Dia.Prompt:new()`.
I just stumbled upon it when i copied the code out of the documentation to test it out.

Good job I really enjoy working with your Fantasy Computer. 
<3

**Comment by poeticAndroid** [comment]
Hey! had to reread that a few times to notice the difference.. :p

it fix now 👍
